spring:
  profiles:
    active: dev
---    
spring:
  profiles: dev     #开发环境
    name: microservicecloud-config-dev
---  
spring:
  profiles: test    #测试环境
  application:
    name: microservicecloud-config-test
    
# 注意保存为utf-8格式